// <auto-generated />
using System;
using Logicfy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Logicfy.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Logicfy.Models.Ders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KisimId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("SoruSayisiCache")
                        .HasColumnType("int");

                    b.Property<int>("TahminiSure")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZorlukSeviyesi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KisimId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("Logicfy.Models.DersPerformansAnalitik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("EnZorSoruId")
                        .HasColumnType("int");

                    b.Property<double>("OrtalamaDogruOrani")
                        .HasColumnType("float");

                    b.Property<double>("OrtalamaTamamlamaSuresi")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.ToTable("DersAnalitigi");
                });

            modelBuilder.Entity("Logicfy.Models.DersTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("TakipEdenKullaniciSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.ToTable("DersTakipleri");
                });

            modelBuilder.Entity("Logicfy.Models.Kisim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DersSayisiCache")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<int>("UniteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UniteId");

                    b.ToTable("Kismlar");
                });

            modelBuilder.Entity("Logicfy.Models.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seviye")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SonGirisTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("Streak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("XP")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciDersIlerleme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("IlerlemeOrani")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("TamamlananSoruSayisi")
                        .HasColumnType("int");

                    b.Property<bool>("TamamlandiMi")
                        .HasColumnType("bit");

                    b.Property<int>("ToplamSoruSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciDersIlerlemeleri");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciDersKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciDersKayitlari");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciGunlukSeri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("SeriSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("SonGiris")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciGunlukSerileri");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciKisimProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlerlemeOrani")
                        .HasColumnType("int");

                    b.Property<int>("KisimId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("TamamlananDersSayisi")
                        .HasColumnType("int");

                    b.Property<int>("ToplamDersSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KisimId");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciKisimProgressleri");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciSoruCevap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CevapJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("DogruMu")
                        .HasColumnType("bit");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<int>("SureMs")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("SoruId");

                    b.ToTable("KullaniciSoruCevaplari");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciUnitProgress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("IlerlemeOrani")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("TamamlananDersSayisi")
                        .HasColumnType("int");

                    b.Property<int>("ToplamDersSayisi")
                        .HasColumnType("int");

                    b.Property<int>("UniteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("UniteId");

                    b.ToTable("KullaniciUnitProgressleri");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciXpLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Xp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("KullaniciXpLoglari");
                });

            modelBuilder.Entity("Logicfy.Models.ProgramlamaDili", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IkonUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProgramlamaDilleri");
                });

            modelBuilder.Entity("Logicfy.Models.Soru", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DersId")
                        .HasColumnType("int");

                    b.Property<int?>("DogruCevapId")
                        .HasColumnType("int");

                    b.Property<string>("EkVeriJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KodMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Seviye")
                        .HasColumnType("int");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoruTipi")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DersId");

                    b.HasIndex("DogruCevapId");

                    b.ToTable("Sorular");
                });

            modelBuilder.Entity("Logicfy.Models.SoruAnalitik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CevaplanmaSayisi")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DogruSayisi")
                        .HasColumnType("int");

                    b.Property<double>("OrtalamaSure")
                        .HasColumnType("float");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YanlisSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.ToTable("SoruAnalitigi");
                });

            modelBuilder.Entity("Logicfy.Models.SoruCanliPreview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DogruCss")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DogruHtml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GerekenEtiketlerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GerekenStillerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SoruId")
                        .IsUnique();

                    b.ToTable("SoruCanliPreviews");
                });

            modelBuilder.Entity("Logicfy.Models.SoruFonksiyonCozum", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CozumKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.ToTable("SoruFonksiyonCozumleri");
                });

            modelBuilder.Entity("Logicfy.Models.SoruKelimeBlok", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DogruKod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KelimelerJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SoruId")
                        .IsUnique();

                    b.ToTable("SoruKelimeBloklari");
                });

            modelBuilder.Entity("Logicfy.Models.SoruSecenek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecenekMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<int?>("SoruId1")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SoruId");

                    b.HasIndex("SoruId1");

                    b.ToTable("SoruSecenekleri");
                });

            modelBuilder.Entity("Logicfy.Models.Unite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DersSayisiCache")
                        .HasColumnType("int");

                    b.Property<int>("ProgramlamaDiliId")
                        .HasColumnType("int");

                    b.Property<int>("Sira")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProgramlamaDiliId");

                    b.ToTable("Uniteler");
                });

            modelBuilder.Entity("Logicfy.Models.UniteTakip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TakipEdenKullaniciSayisi")
                        .HasColumnType("int");

                    b.Property<int>("UniteId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("UniteId");

                    b.ToTable("UniteTakipleri");
                });

            modelBuilder.Entity("Logicfy.Models.Ders", b =>
                {
                    b.HasOne("Logicfy.Models.Kisim", "Kisim")
                        .WithMany("Dersler")
                        .HasForeignKey("KisimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisim");
                });

            modelBuilder.Entity("Logicfy.Models.DersPerformansAnalitik", b =>
                {
                    b.HasOne("Logicfy.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Logicfy.Models.DersTakip", b =>
                {
                    b.HasOne("Logicfy.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");
                });

            modelBuilder.Entity("Logicfy.Models.Kisim", b =>
                {
                    b.HasOne("Logicfy.Models.Unite", "Unite")
                        .WithMany("Kismlar")
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciDersIlerleme", b =>
                {
                    b.HasOne("Logicfy.Models.Ders", "Ders")
                        .WithMany()
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logicfy.Models.Kullanici", "Kullanici")
                        .WithMany("DersIlerlemeleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciDersKaydi", b =>
                {
                    b.HasOne("Logicfy.Models.Ders", "Ders")
                        .WithMany("DersKayitlari")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logicfy.Models.Kullanici", "Kullanici")
                        .WithMany("DersKayitlari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ders");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciGunlukSeri", b =>
                {
                    b.HasOne("Logicfy.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciKisimProgress", b =>
                {
                    b.HasOne("Logicfy.Models.Kisim", "Kisim")
                        .WithMany()
                        .HasForeignKey("KisimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logicfy.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisim");

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciSoruCevap", b =>
                {
                    b.HasOne("Logicfy.Models.Kullanici", "Kullanici")
                        .WithMany("SoruCevaplari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logicfy.Models.Soru", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciUnitProgress", b =>
                {
                    b.HasOne("Logicfy.Models.Kullanici", "Kullanici")
                        .WithMany()
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logicfy.Models.Unite", "Unite")
                        .WithMany()
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("Logicfy.Models.KullaniciXpLog", b =>
                {
                    b.HasOne("Logicfy.Models.Kullanici", "Kullanici")
                        .WithMany("XpLoglari")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Logicfy.Models.Soru", b =>
                {
                    b.HasOne("Logicfy.Models.Ders", "Ders")
                        .WithMany("Sorular")
                        .HasForeignKey("DersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logicfy.Models.SoruSecenek", "DogruCevap")
                        .WithMany()
                        .HasForeignKey("DogruCevapId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ders");

                    b.Navigation("DogruCevap");
                });

            modelBuilder.Entity("Logicfy.Models.SoruAnalitik", b =>
                {
                    b.HasOne("Logicfy.Models.Soru", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("Logicfy.Models.SoruCanliPreview", b =>
                {
                    b.HasOne("Logicfy.Models.Soru", "Soru")
                        .WithOne()
                        .HasForeignKey("Logicfy.Models.SoruCanliPreview", "SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("Logicfy.Models.SoruFonksiyonCozum", b =>
                {
                    b.HasOne("Logicfy.Models.Soru", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("Logicfy.Models.SoruKelimeBlok", b =>
                {
                    b.HasOne("Logicfy.Models.Soru", "Soru")
                        .WithOne()
                        .HasForeignKey("Logicfy.Models.SoruKelimeBlok", "SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("Logicfy.Models.SoruSecenek", b =>
                {
                    b.HasOne("Logicfy.Models.Soru", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Logicfy.Models.Soru", null)
                        .WithMany("Secenekler")
                        .HasForeignKey("SoruId1");

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("Logicfy.Models.Unite", b =>
                {
                    b.HasOne("Logicfy.Models.ProgramlamaDili", "ProgramlamaDili")
                        .WithMany("Uniteler")
                        .HasForeignKey("ProgramlamaDiliId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProgramlamaDili");
                });

            modelBuilder.Entity("Logicfy.Models.UniteTakip", b =>
                {
                    b.HasOne("Logicfy.Models.Unite", "Unite")
                        .WithMany()
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("Logicfy.Models.Ders", b =>
                {
                    b.Navigation("DersKayitlari");

                    b.Navigation("Sorular");
                });

            modelBuilder.Entity("Logicfy.Models.Kisim", b =>
                {
                    b.Navigation("Dersler");
                });

            modelBuilder.Entity("Logicfy.Models.Kullanici", b =>
                {
                    b.Navigation("DersIlerlemeleri");

                    b.Navigation("DersKayitlari");

                    b.Navigation("SoruCevaplari");

                    b.Navigation("XpLoglari");
                });

            modelBuilder.Entity("Logicfy.Models.ProgramlamaDili", b =>
                {
                    b.Navigation("Uniteler");
                });

            modelBuilder.Entity("Logicfy.Models.Soru", b =>
                {
                    b.Navigation("Secenekler");
                });

            modelBuilder.Entity("Logicfy.Models.Unite", b =>
                {
                    b.Navigation("Kismlar");
                });
#pragma warning restore 612, 618
        }
    }
}
